name = "Unzip"
uuid = "41fe7b60-77ed-43a1-b4f0-825fd5a5650d"
authors = ["Brandon Taylor <brandon.taylor221@gmail.com> and contributors"]
version = "0.2.0"

[compat]
julia = "1.7"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Documenter", "OffsetArrays", "Test"]
